version: 1
packages:
  - version: commit:6a557d278b67966366f27f288e5370fcea4863a6
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
