version: 1
packages:
  - version: commit:bef8cbe8597e557cbd81a0ff4e85366620e14e9e
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
