version: 1
packages:
  - version: commit:aeb6ea9896fff0f4fefb8673fdf3a627729b28d7
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
