version: 1
packages:
  - version: commit:65f9635849b87e16ae6cc5921a9d119ceeef2cc7
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
