version: 1
packages:
  - version: commit:f6dc87b5018042248b0c5419ccb074139fd75d6e
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
