version: 1
packages:
  - version: commit:813ac10e85a6b04bca5eb6d77350df6c4f2ec90c
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
