version: 1
packages:
  - version: commit:0906e3621ce0f843392b23f2d13f9a3dc3c6bed4
    name: Common-Objects
    url: https://github.com/muellermarco/sml-salesinsights-common.git
    branch: databricks
